name: flutter_github
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphql_dart: any
  http: ^0.12.0+1
  bloc: ^0.14.1
  responsive_scaffold: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  graphql_client_generator: any
  build_runner: ^1.1.2
  built_value_generator: ^6.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/.github_key.txt

dependency_overrides:
  graphql_client_generator:
    git:
      url: git@github.com:rtafleet/graphql_client_gen_dart.git
      path: graphql_client_generator
  graphql_dart:
    git:
      url: git@github.com:rtafleet/graphql_client_gen_dart.git
      path: graphql_dart
